AWSTemplateFormatVersion: '2010-09-09'
Description: RDS Log Dog lambda function
Parameters:
  s3bucket:
    Type: String
    Description: s3 bucket for logs and code
  s3key: 
    Type: String
    Description: lambda code zip
Resources:
  function:
    Type: "AWS::Lambda::Function"
    Properties: 
      Description: RDS Log Dog function
      Code:
        S3Bucket: '|ref|s3bucket'
        S3Key: '|ref|s3key'
      Environment:
        Variables:
          dstBucket: '|ref|s3bucket'
      Handler: handler
      #KmsKeyArn: String
      Role: lambda_basic_execution
      Runtime: python2.7
      #Timeout: Integer
